dcConsData = [		
	{name:"매칭망겜.png", keywords:["매칭망겜" ,"망겜"], tags:["스플"]},
	{name:"질병게임.png", keywords:["질병게임" ,"질병"], tags:["스플"]},
	{name:"주작기온.png", keywords:["주작기온" ,"주작기"], tags:["스플"]},
	{name:"스플깨짐.png", keywords:["스플깨짐" ,"깨짐"], tags:["스플"]},
	{name:"스플닌자.png", keywords:["스플닌자" ,"닌자"], tags:["스플"]},
	{name:"스플로봇.png", keywords:["스플로봇" ,"로봇"], tags:["스플"]},
	{name:"스플쉴드.png", keywords:["스플쉴드" ,"쉴드"], tags:["스플"]},
	{name:"스플눈물.png", keywords:["스플눈물" ,"눈물"], tags:["스플"]},
	{name:"스플웃음.png", keywords:["스플웃음" ,"웃음"], tags:["스플"]},
	{name:"스플컷.png", keywords:["스플컷" ,"컷"], tags:["스플"]},
	{name:"스플핑.png", keywords:["스플핑" ,"핑"], tags:["스플"]},
	{name:"스플컬링.png", keywords:["스플컬링" ,"컬링"], tags:["스플"]},
	{name:"스플승리.png", keywords:["스플승리" ,"승리"], tags:["스플"]},
	{name:"스플패배.png", keywords:["스플패배" ,"패배"], tags:["스플"]},
	{name:"스플존.png", keywords:["스플존" ,"에리어"], tags:["스플"]},
	{name:"스플타워.png", keywords:["스플타워" ,"야구라"], tags:["스플"]},
	{name:"스플호코.png", keywords:["스플호코" ,"호코"], tags:["스플"]},
	{name:"스플조개.png", keywords:["스플조개" ,"아사리"], tags:["스플"]},
	{name:"스시좋아.png", keywords:["스시좋아" ,"스시"], tags:["스플"]},
	{name:"스플3.gif", keywords:["스플3" ,"스플래툰3"], tags:["스플"]},
	{name:"스플가챠.gif", keywords:["스플가챠" ,"가챠"], tags:["스플"]},
	{name:"스플차단.gif", keywords:["스플차단" ,"차단"], tags:["스플"]},
	{name:"스플깨짐2.gif", keywords:["스플깨짐2"], tags:["스플"]},
	{name:"스플금.gif", keywords:["스플금" ,"금"], tags:["스플"]},

	{name:"슈퍼소닉.gif", keywords:["슈퍼소닉"], tags:["소닉"]},
	{name:"소닉윙크.gif", keywords:["소닉윙크"], tags:["소닉"]},
	{name:"소닉신작.gif", keywords:["소닉신작"], tags:["소닉"]},
	{name:"소닉풉.png", keywords:["소닉풉" ,"풉"], tags:["소닉"]},

	{name:"편안.png", keywords:["편안"], tags:["기타"]},
	{name:"불편.png", keywords:["불편"], tags:["기타"]},
	{name:"펄럭.png", keywords:["펄럭"], tags:["기타"]}
];
