dcConsData = [		
	{name:"스플전멸.png", keywords:["스플전멸"], tags:["스플"]},
	{name:"스플눈물.png", keywords:["스플눈물" ,"눈물"], tags:["스플"]},
	{name:"스플웃음.png", keywords:["스플웃음" ,"웃음"], tags:["스플"]},
	{name:"스플컷.png", keywords:["스플컷" ,"컷"], tags:["스플"]},
	{name:"스플핑.png", keywords:["스플핑" ,"핑"], tags:["스플"]},
	{name:"스플승리.png", keywords:["스플승리" ,"승리"], tags:["스플"]},
	{name:"스플패배.png", keywords:["스플패배" ,"패배"], tags:["스플"]},
	{name:"스플존.png", keywords:["스플존" ,"에리어"], tags:["스플"]},
	{name:"스플타워.png", keywords:["스플타워" ,"야구라"], tags:["스플"]},
	{name:"스플호코.png", keywords:["스플호코" ,"호코"], tags:["스플"]},
	{name:"스플조개.png", keywords:["스플조개" ,"스플아사리" ,"아사리"], tags:["스플"]},
	{name:"스시좋아.png", keywords:["스시좋아" ,"스시"], tags:["스플"]},
	{name:"연어알.png", keywords:["연어알"], tags:["스플"]},
	{name:"황금알.png", keywords:["황금알"], tags:["스플"]},
	{name:"아사리패스.png", keywords:["아사리패스" ,"패스"], tags:["스플"]},
	{name:"혐레이.png", keywords:["혐레이" ,"모레이" ,"모래이"], tags:["스플"]},
	{name:"혐핑장.png", keywords:["혐핑장" ,"캠핑장" ,"캠프"], tags:["스플"]},
	{name:"혐로와나.png", keywords:["혐로와나" ,"아로와나" ,"아로아나"], tags:["스플"]},
	{name:"혐배스.png", keywords:["혐배스" ,"비배스" ,"비베스" ,"비바스" ,"B배스 파크"], tags:["스플"]},
	{name:"혐호텔.png", keywords:["혐호텔" ,"망호텔" ,"호텔" ,"호텔 뉴 오토로"], tags:["스플"]},
	{name:"스메시 월드.png", keywords:["스메시 월드" ,"놀이동산" ,"ㄹ머라"], tags:["스플"]},
	{name:"스플클블.gif", keywords:["스플클블" ,"클블"], tags:["스플"]},
	{name:"연어도움.gif", keywords:["연어도움" ,"도움"], tags:["스플"]},
	{name:"연어빙글.gif", keywords:["연어빙글" ,"빙글"], tags:["스플"]},
	{name:"연어빙글2.gif", keywords:["연어빙글2" ,"빙글2"], tags:["스플"]},
	{name:"호코골인.gif", keywords:["호코골인" ,"골인"], tags:["스플"]},
	{name:"호코골인2.gif", keywords:["호코골인2" ,"골인2"], tags:["스플"]},
	{name:"스플3.gif", keywords:["스플3" ,"스플래툰3"], tags:["스플"]},
	{name:"스플증발.gif", keywords:["스플증발" ,"증발"], tags:["스플"]},
	{name:"스플슬롯.gif", keywords:["스플슬롯" ,"슬롯"], tags:["스플"]},
	{name:"스플빠짐.gif", keywords:["스플빠짐"], tags:["스플"]},
	{name:"스플차단.gif", keywords:["스플차단" ,"차단"], tags:["스플"]},
	{name:"스플달다.gif", keywords:["스플달다" ,"달다"], tags:["스플"]},
	{name:"스플깨짐.gif", keywords:["스플깨짐" ,"깨짐"], tags:["스플"]},
	{name:"스플세이프.gif", keywords:["스플세이프" ,"세이프"], tags:["스플"]},
	{name:"스플금.gif", keywords:["스플금" ,"금"], tags:["스플"]},
	{name:"스플좁쌀.png", keywords:["좁쌀"], tags:["스플"]},
	{name:"X랭.gif", keywords:["엑스랭" ,"액스랭" ,"x랭" ,"X랭"], tags:["스플"]},
	{name:"X포즈.gif", keywords:["엑스포즈" ,"액스포즈" ,"x포즈" ,"X포즈"], tags:["스플"]},
	{name:"배터리없.gif", keywords:["베터리없" ,"배터리없" ,"충전"], tags:["스플"]},
	{name:"친추차단.gif", keywords:["친추차단" ,"친추"], tags:["스플"]},

	{name:"슈퍼소닉.gif", keywords:["슈퍼소닉"], tags:["소닉"]},
	{name:"소닉윙크.gif", keywords:["소닉윙크"], tags:["소닉"]},
	{name:"소닉신작.gif", keywords:["소닉신작"], tags:["소닉"]},
	{name:"소닉트릭.gif", keywords:["소닉트릭"], tags:["소닉"]},
	{name:"소닉추락.gif", keywords:["소닉추락"], tags:["소닉"]},
	{name:"소닉놀람.gif", keywords:["소닉놀람"], tags:["소닉"]},
	{name:"3d소닉.gif", keywords:["3d소닉"], tags:["소닉"]},
	{name:"싸닉.png", keywords:["싸닉"], tags:["소닉"]},
	{name:"소닉풉.png", keywords:["소닉풉" ,"풉"], tags:["소닉"]},

	{name:"8하.gif", keywords:["8하" ,"팔하"], tags:["805"]},
	{name:"8바.gif", keywords:["8바" ,"팔바"], tags:["805"]},
	{name:"팔공응원.gif", keywords:["팔공응원" ,"80응원" ,"응원"], tags:["805"]},
	{name:"팔공끝.png", keywords:["팔공끝" ,"끝"], tags:["805"]},
	{name:"팔공퉤.png", keywords:["팔공퉤" ,"퉤"], tags:["805"]},
	{name:"팔공퉤2.png", keywords:["팔공퉤2" ,"퉤2"], tags:["805"]},
	{name:"팔공망겜.png", keywords:["팔공망겜"], tags:["805"]},
	{name:"팔공하하.png", keywords:["팔공하하"], tags:["805"]},
	{name:"팔공짜다.png", keywords:["팔공짜다" ,"짜다"], tags:["805"]},
	{name:"팔공몰루.png", keywords:["팔공몰루" ,"팔?공"], tags:["805"]},

	{name:"페페오열.png", keywords:["페페오열" ,"오열페페"], tags:["페페"]},

	{name:"관짝준비.gif", keywords:["관짝준비"], tags:["기타"]},
	{name:"관짝댄스.gif", keywords:["관짝댄스"], tags:["기타"]},
	{name:"불사람.gif", keywords:["불사람"], tags:["기타"]},
	{name:"광클.gif", keywords:["광클"], tags:["기타"]},
	{name:"식은땀.gif", keywords:["식은땀"], tags:["기타"]},
	{name:"제리인사.gif", keywords:["제리인사"], tags:["기타"]},
	{name:"톰인사.gif", keywords:["톰인사"], tags:["기타"]},
	{name:"레고불편.png", keywords:["레고불편"], tags:["기타"]},
	{name:"입틀막.png", keywords:["입틀막"], tags:["기타"]},
	{name:"즐겁다.png", keywords:["즐겁다"], tags:["기타"]},
	{name:"편안.png", keywords:["편안"], tags:["기타"]},
	{name:"불편.png", keywords:["불편"], tags:["기타"]},
	{name:"ㄴㅇㄱ.png", keywords:["ㄴㅇㄱ"], tags:["기타"]},
	{name:"펄럭.png", keywords:["펄럭"], tags:["기타"]}
];
